config/routes.rb
Rails.application.routes.draw do
  resources :post_attachments
  root to: "home#index"
  devise_for :users
  resources :blogs do
    resources :comments
  end
  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	belongs_to :user
	validates :title, presence: true
	mount_uploader :image, AvatarUploader
	extend FriendlyId
  friendly_id :title, use: :slugged
   has_many :comments
   has_many :post_attachments
   accepts_nested_attributes_for :post_attachments
   has_many :playlists

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :blog
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
	belongs_to :blog
	extend FriendlyId
  friendly_id :link, use: :slugged
end

app/models/post_attachment.rb
class PostAttachment < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
   belongs_to :blog
   extend FriendlyId
  friendly_id :avatar, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :blogs
	validates :email, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def configure_permitted_parameters

  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :date_of_birth, :gender) }
  	devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email) }
	end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	before_action :set_blog, only: [:show, :edit, :update, :destroy]

	def index
		@blogs = Blog.all
	end

	def new
		@blog = Blog.new
		@post_attachment = @blog.post_attachments.build
	end

	def show
		@post_attachments = @blog.post_attachments.all
	end

	def edit
	end

	def create
		@blog = Blog.new(blog_params)
		if @blog.save
			params[:post_attachments]['avatar'].each do |a|
          @post_attachment = @blog.post_attachments.create!(:avatar => a)
      end
       redirect_to blog_path(@blog)
     else
       render action: 'new'
     end
   end

	def update
		if @blog.update(blog_params)
			redirect_to blog_path(@blog)
		else
			render :edit
		end
	end

	def destroy
		@blog.destroy
		redirect_to blogs_path
	end

	private
	def blog_params
		params.require(:blog).permit(:title, :discription,:image, {avatars: []}, :youtube_url,  post_attachments_attributes: [:id, :blog_id, :avatar])
	end

	def set_blog
		@blog = Blog.friendly.find(params[:id])
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_blog, only: [:index, :new, :show, :edit, :create, :update, :destroy]
	 
	def index
		@comment = @blog.comments
		respond_to do |format|
			if @comment.save
				format.html {redirect_to blog_path(@blog)} 
      	format.js {redirect_to blog_path(@blog)}
   		else
      	format.html { render :action => 'new' }
      	format.js { render :action => 'new' }
    	end
		end
	end

	def new
		@comment = @blog.comment.new
	end

	def show
	end

	def edit
	end

	def create
		@comment = @blog.comments.build(comment_params)
		if @comment.save
        format.html { redirect_to @comment, notice: 'comment was successfully upload.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

	def update
		if @comment.update(comment_params)
			redirect_to blog_path(@blog)
		else
			render :edit
		end
	end

	def destroy
		@comment.destroy
		redirect_to blog_path(@blog)
	end

	private
	def comment_params
		params.require(:comment).permit(:comment, :blog_id)
	end

	def set_blog
		@blog = Blog.friendly.find(params[:blog_id])
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	 def index
	 end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

	before_action :set_playlist, only: [:show, :edit, :update, :destroy] 

	def index
		@playlists = Playlist.all
	end

	def new
		@playlist = Playlist.new
	end

	def show
	end

	def edit
	end

	def create
		@playlist = Playlist.new(playlist_params)
			respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'video was successfully upload.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
	end

	def update
		respond_to do |format|
			if @playlist.update(playlist_params)
				format.html { redirect_to @playlist, notice: 'video was successfully updated.' }
	    end 
  	end
	end

	def destroy
		respond_to do |format|
			if @playlist.destroy
				format.html { redirect_to @playlist, notice: 'video was successfully updated.' }
	    end 
  	end
  end

	private

	def set_playlist
		@playlist = Playlist.friendly.find(params[:id])
	end

	def playlist_params
		params.require(:playlist).permit(:link, :video_title, :author, :likes, :dis_likes)
	end
end

app/controllers/post_attachments_controller.rb
class PostAttachmentsController < ApplicationController
  before_action :set_post_attachment, only: [:show, :edit, :update, :destroy]

  # GET /post_attachments
  # GET /post_attachments.json
  def index
    @post_attachments = PostAttachment.all
  end

  # GET /post_attachments/1
  # GET /post_attachments/1.json
  def show
  end

  # GET /post_attachments/new
  def new
    @post_attachment = PostAttachment.new
  end

  # GET /post_attachments/1/edit
  def edit
  end

  # POST /post_attachments
  # POST /post_attachments.json
  def create
    @post_attachment = PostAttachment.new(post_attachment_params)

    respond_to do |format|
      if @post_attachment.save
        format.html { redirect_to @post_attachment, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @post_attachment }
      else
        format.html { render :new }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_attachments/1
  # PATCH/PUT /post_attachments/1.json
  def update
  respond_to do |format|
    if @post_attachment.update(post_attachment_params)
      format.html { redirect_to @post_attachment.blog, notice: 'Image was successfully updated.' }
    end 
  end
end

  # DELETE /post_attachments/1
  # DELETE /post_attachments/1.json
  def destroy
    @post_attachment.destroy
    respond_to do |format|
      format.html { redirect_to post_attachments_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_attachment
      @post_attachment = PostAttachment.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_attachment_params
      params.require(:post_attachment).permit(:blog_id, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	 def tinymce_assets
	      javascript_include_tag "tinymce"
	 end

	def embed(youtube_url)
		#youtube_url = "http://www.youtube.com/watch?v=DokUjuZmpCE";
		if youtube_url.include? '='
			youtube_id = youtube_url.split("=").last
		else
  	  youtube_id = youtube_url.split("/").last
  	end
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
	def embed(link)
		#youtube_url = "http://www.youtube.com/watch?v=DokUjuZmpCE";
		if link.include? '='
			youtube_id = link.split("=").last
		else
  	  youtube_id = link.split("/").last
  	end
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
  end
end

app/helpers/post_attachments_helper.rb
module PostAttachmentsHelper
end

app/views/blogs/_form.html.erb
<div class="container">
  <div class="col-md-6">
  <%= form_for :blog,:html => {:multipart => true}, url: blogs_path do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@blog.errors.count, "error") %> prohibited
        this blog from being saved:
      </h2>
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :title %><br />
    <%= f.text_field :title, :class => 'form-group col-md-12' %>
  </div>
  
  <div class="panel-heading head-border">
  	<%= f.label :discription %><br />
  	<%= f.text_area :discription, :class => "tinymce", :rows => 5, :cols => 2 %>
  </div>

  <div class="form-group">
    <%= f.label :youtube_url %><br />
    <%= f.text_field :youtube_url, :class => 'form-group col-md-12' %>
  </div>


  <%= f.fields_for :post_attachments do |p| %>
     <div class="field">
       <%= p.label :Image %><br>
       <%= p.file_field :avatar, :multiple => true, name: "post_attachments[avatar][]" %>
     </div>
   <% end %>

  <div class="actions">
    <%= f.submit "submit", :class => 'btn btn-primary' %>
  </div> 
  <% end %>
  </div>
  </div>

  <script type="text/javascript">
  tinyMCE.init({
    selector: '#blog_discription',
   
      force_br_newlines : false,
      force_p_newlines : false,
      forced_root_block : '',
  });
  
</script>

app/views/blogs/edit.html.erb
<h1 class='container'>Edit Blog</h1>
<%= render 'form' %>

app/views/blogs/index.html.erb
<h1 class="panel-heading">Blog</h1>
<%= link_to "New Blog", new_blog_path, :class => "btn btn-info" %>
<table class="table table-hover">
  <tr>
    <th>Title</th>
    <th>Discription</th>
    <th colspan=6></th>
  </tr>
    <% @blogs.each do |blog| %>
    <tr>
  	<td><%= blog.title %></td>
  	<td><%= blog.discription %></td>
    <td><%= link_to 'Show', blog_path(blog), :class=> 'btn btn-success' %>
    </td>
    <td><%= link_to 'Edit', edit_blog_path(blog), :class => 'btn btn-info' %></td>
    <td><%= link_to 'Delete', blog_path(blog), method: :delete,data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td> 
  </tr>
  <% end %>
  </table>

app/views/blogs/new.html.erb
<h1 class='container'>Blog</h1>
<%= render 'form' %>

app/views/blogs/show.html.erb
<div class = "container">
<section>
  <div class="panel panel-primary">
    <div class="panel-body">
    	<div class="row">
        <div class="col-lg-6 col-sm-4">
					<div class="col-lg-4 col-sm-4">
						<strong class="text-center">Title:</strong>
						<%= @blog.title %>
						<strong>Discription:</strong>
						<%= @blog.discription %>
						<strong>Image:</strong><br />
						<%#= image_tag @blog.image_url.to_s,:size => "180x180" %>
						<% @post_attachments.each do |p| %>
  						<%= image_tag p.avatar_url, :size => "180x180" %>
  						<%= link_to 'New image', new_post_attachment_path, :class => "btn btn-default" %><br />
  						<%= link_to "Update Image", edit_post_attachment_path(p), :class => "btn btn-default" %><br />
						<% end %>
						<strong>youtube_url:</strong><br /> 
						<%= embed(@blog.youtube_url) rescue 0 %>
						<%= link_to "Playlist", new_playlist_path %>
						<%= link_to "All Videos" playlists_path %>
 						<div id="blog_comments">
							<%= render 'comments/comment' %>
						</div>
						<%= render "comments/form" %>
						<%= link_to "Back", blogs_path %>
					</div>
				</div>
			</div>
		</div>
	</div>
</section> 

app/views/comments/_comment.html.erb
<div id="notice"><%= notice %></div>
<% @blog.comments.each do |comment| %>
	<div class = "container">
		<span id="comment_<%= comment.id %>">
			<%= comment.comment %>
		</span> 
	</div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [@blog, @blog.comments.build],:remote => true do |f| %>
<div class = "form-group">
	<%= f.label :comment %>
	<%= f.text_field :comment, :class => 'form-group' %>
</div>
<div class="actions">
	<%= f.submit "save", :class => 'btn btn-info' %>
</div>
<% end %>

app/views/comments/create.js.erb
$("#blog_comments").html("<%= escape_javascript(render(:partial => 'comments/comment')) %>");
$('#comment_comment').val('')

app/views/comments/index.html.erb
<h1>Comment</h1>

app/views/comments/new.html.erb
<h1>Comment</h1>

app/views/home/index.html.erb
<h1>BLog App</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "customjsFile", "data-turbolinks-track" => true  %>

  <%= csrf_meta_tags %>
</head>

<body>
<nav class="navbar navbar-inverse">
  <div class="collection">
      <div class="navbar-header">
      <a class="navbar-brand" >BLogApp</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li>
        <% if user_signed_in? %>
        <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
        <% else %>
        <li>
        <%= link_to 'Sign up', new_user_registration_path %></li>
        <li><%= link_to 'Login', new_user_session_path %></li>
        </li>
        <li class="active"><%= link_to 'New Blog', new_blog_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<%= yield %>
<% if user_signed_in? %>
<div>Signed in as... <%= current_user.email %></div>
  
<% end %>
</body>
</html>

app/views/playlists/_form.html.erb
<div class="container" >
<div class="row">
<h2>Add videos Here</h2>
<%= form_for @playlist do |f| %>
	<% if @playlist.errors.any? %>
	    <div id="error_explanation">
	      <h2>
	        <%= pluralize(@playlist.errors.count, "error") %> prohibited
	        this playlist from being saved:
	      </h2>
	      <ul>
	        <% @playlist.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	        <% end %>
	      </ul>
	    </div>
	  <% end %>
	<div class="form-group">
		<%= f.label :link %>
		<%= f.text_field :link, :class =>'form-group' %>
	</div>
	<div class="form-group">
		<%= f.label :video_title %>
		<%= f.text_field :video_title, :class =>'form-group' %>
	</div>
	<div class="form-group">
		<%= f.label :author %>
		<%= f.text_field :author, :class =>'form-group' %>
	</div>
	<div class="form_group">
		<%= f.hidden_field :blog %>
	</div>
	<div class="actions">
		<%= f.submit "submit", :class => 'btn btn-primary' %>
	</div>
<% end %>

app/views/playlists/edit.html.erb
<%= render 'form' %>

app/views/playlists/index.html.erb
<div class="container">
<h1 class="center-text">Playlist</h1>
<%= link_to "add Video", new_playlist_path, :class => 'btn btn-danger' %>
<table class="table table-hover">
  <thead>
    <tr>
      <th colspan="1"></th>
    </tr>
  </thead>
  <% @playlists.each do |playlist| %>
  <tr>
  	<th><%= embed(playlist.link) %></th>
  	<th>Title:<%= playlist.video_title %></th>
  	<th>Author:<%= playlist.author %></th>
  	<th>Likes:<%= playlist.likes %></th>
  	<th>Dislikes:<%= playlist.dis_likes %></th>
  	<th><%= link_to 'play', playlist_path(playlist), :class => 'btn btn-danger' %></th>
  </tr>
  <% end %>
</table>

app/views/playlists/new.html.erb
<%= render 'form' %>	

app/views/playlists/show.html.erb
<div class="container">
<div id="notice"><%= notice %></div>
	<strong>Link:</strong><br />
		<div class="embed-container">
			<%= embed(@playlist.link) %><br />
		</div>
<%= link_to "all Video", playlists_path %>

app/views/post_attachments/_form.html.erb
<div class="container">
<%= form_for(@post_attachment) do |f| %>
  <% if @post_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_attachment.errors.count, "error") %> prohibited this post_attachment from being saved:</h2>

      <ul>
      <% @post_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :avatar %>
  </div>
  <div>
    <%= f.hidden_field :blog_id, :value => @blog %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_attachments/edit.html.erb
<div class="container">
<h1>Editing Post Attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_attachment %> |
<%= link_to 'Back', post_attachments_path %>

app/views/post_attachments/index.html.erb
<div class="container">
<section>
  <div class="panel panel-primary">
    <div class="panel-body">
      <div class="row">
        <div class="col-lg-4 col-sm-4">
          <div class="col-lg-4 col-sm-4">
            <p id="notice"><%= notice %></p>
                <h1 class="center-text">Images</h1>
              </div>
              <table>
                <thead>
                  <tr>
                    <th colspan="3"></th>
                  </tr>
                </thead>
              <tbody>
                <% @post_attachments.each do |post_attachment| %>
                  <tr>
                  <div class="container">
                    <ul class="row">
                    <div class="col-sm-6 col-md-4">

                      <td class="thumbnail"><%= image_tag(post_attachment.avatar_url(:thumb).to_s) %></td>
                    </ul>
                  </div>
                  <td><%= link_to 'Show', post_attachment, :class => "btn btn-info" %> | </td> 
                  <td><%= link_to 'Edit', edit_post_attachment_path(post_attachment), :class => 'btn btn-primary' %> | </td>  
                  <td><%= link_to 'Destroy', post_attachment, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
                    
                  </tr>
                <% end %>
              </tbody>
            </table>
            <br>
            <%= link_to 'New Post attachment', new_post_attachment_path, :class => 'btn btn-info' %>
          </div>
        </div>
      </div>
    </div>
    </div>

app/views/post_attachments/new.html.erb
<div class="container">
<h1>Images</h1>

<%= render 'form' %>

<%= link_to 'Back', post_attachments_path %>

app/views/post_attachments/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<div class="well">
  <strong>Image:</strong><br />
  <%= image_tag @post_attachment.avatar %>
</p>

<%= link_to 'Edit', edit_post_attachment_path(@post_attachment), :class => "btn btn-primary" %> |
<%= link_to 'Back', post_attachments_path, :class => "btn btn-danger" %>
</div>